version: '3.8'

services:
  front:
    build: 
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "3000:3000"

    container_name: home-page

    command: bash -c "cd ./homepage-docker && git pull && npm i && npm start"